//
// Created by Hugo on 24/04/2026.
//

#ifndef CARENTERTAINMENTSYSTEM_FMPLAYERVIEW_H
#define CARENTERTAINMENTSYSTEM_FMPLAYERVIEW_H


class FMPlayerView {
};


#endif //CARENTERTAINMENTSYSTEM_FMPLAYERVIEW_H
